dyapp/urls.py
from django.urls import path
from dyapp.views import *

urlpatterns = [
    path('', IndexView.as_view(), name="home"),
    path('dyform/new/',BuildView.as_view(), name="form_create"),
    path('dyform/<int:form_id>/',DyformDetailView.as_view(), name="form_detail"),
    path('dyform/<int:form_id>/edit/',DyformEditView.as_view(), name="form_edit"),
    path('dyform/<int:form_id>/response/',RespondView.as_view(), name="form_respond"),
    path('dyform/<int:form_id>/response/<int:response_id>/',RespondView.as_view(), name="response"),
]

dyformnew/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dyapp.urls')),
    # path('', include('forms_builder.forms.urls')),
]

dyapp/models.py
from django.db import models
from dynamic_forms.models import FormField, ResponseField
from datetime import datetime


class Dyforms(models.Model):
    form_name = models.CharField(max_length=100)
    form_number = models.BigIntegerField(null=True,blank=True)
    form_id = models.BigIntegerField(null=True,blank=True)
    form_time = models.DateTimeField(auto_now=True,null=True,blank=True)

    form = FormField()

    def __str__(self):
        return "Form #{}: {}".format(self.pk, self.form_name)


class FormResponse(models.Model):
    form = models.ForeignKey(Dyforms, on_delete=models.CASCADE)
    response = ResponseField()

dynamic_forms/models.py
import json

from django.db import models
from .formfields import FormBuilderField, FormRenderField


class FormField(models.TextField):
    """Stores JSON Schema for form
    """

    def from_db_value(self, value, expression, connection):
        if value is None:
            return []
        return json.loads(value)

    def to_python(self, value):
        if isinstance(value, list):
            return value
        return json.loads(value)

    def get_prep_value(self, value):
        if isinstance(value, str) or value is None:
            return value
        return json.dumps(value)

    def formfield(self, **kwargs):
        kwargs['form_class'] = FormBuilderField
        return super().formfield(**kwargs)


class ResponseField(models.TextField):
    """Stores JSON response to form.
    """

    def from_db_value(self, value, expression, connection):
        if value is None:
            return value
        return json.loads(value)

    def to_python(self, value):
        if isinstance(value, dict):
            return value
        if value is None:
            return {}
        return json.loads(value)

    def get_prep_value(self, value):
        if isinstance(value, str) or value is None:
            return value
        # Datetime.date is not JSON serializable, so must specify to convert to string
        return json.dumps(value, default=str)

    def formfield(self, *args, **kwargs):
        kwargs['form_class'] = FormRenderField
        return super().formfield(*args, **kwargs)

dyapp/forms.py
from django import forms
from django.forms.utils import ErrorList

from dyapp.models import *

class FormResponseform(forms.ModelForm):
    class Meta:
        model = FormResponse
        fields = '__all__'

dyapp/views.py
from django.shortcuts import render
from dyapp.forms import *
from dyapp.models import *
from django.urls import reverse
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from dynamic_forms.views import DynamicFormMixin

# Create your views here.

class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = Dyforms.objects.all()
        return context


class BuildView(CreateView):
    model = Dyforms
    fields = '__all__'
    template_name = "build.html"
    success_url = "/"


class DyformDetailView(DetailView):
    model = Dyforms
    pk_url_kwarg = "form_id"
    template_name = "form_detail.html"


class DyformEditView(UpdateView):
    model = Dyforms
    fields = '__all__'
    pk_url_kwarg = "form_id"
    template_name = "form_edit.html"

    def get_success_url(self):
        return reverse('form_detail', kwargs={"form_id": self.object.pk})


class RespondView(DynamicFormMixin, CreateView):
    model = FormResponse
    fields = ['response']
    template_name = "respond.html"

    form_model = Dyforms
    form_pk_url_kwarg = "form_id"
    response_form_fk_field = "form"
    response_field = "response"

    def get_success_url(self):
        return reverse('form_detail', kwargs={"form_id": self.form_instance.pk})

dynamic_forms/views.py
from django.views.generic.edit import FormMixin


class DynamicFormMixin(FormMixin):
    form_field = "form"
    form_pk_url_kwarg = "pk"

    response_form_fk_field = None
    response_field = "response"

    def _get_object_containing_form(self, pk):
        return self.form_model.objects.get(pk=pk)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        # Get instance of model containing form used for this response. Save this object as an instance variable for use in form_valid method
        form_instance_pk = self.kwargs[self.form_pk_url_kwarg]
        self.form_instance = self._get_object_containing_form(form_instance_pk)
        # Get json form configuration from form-containing object
        json_data = getattr(self.form_instance, self.form_field)
        # Add fields in JSON to dynamic form rendering field.
        form.fields[self.response_field].add_fields(json_data)
        return form

    def form_valid(self, form):
        action = form.save(commit=False)
        setattr(action, self.response_form_fk_field, self.form_instance)
        action.save()
        return super().form_valid(form)

dynamic_forms/templates/dynamic_forms/widgets/formbuilder.html
<fieldset><div id="fb-editor"></div></fieldset>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
<script>
    $(document).ready(function () {
        var textArea = $('[name="{{ widget.name }}"]')
        var options = {
            disabledActionButtons: ['save'],
            disabledAttrs: [
                'access',
                'name',
                'className',
                'inline',
                'other',
            ],
            disabledSubtypes: {
                text: ['color', 'tel', 'password'],
                textarea: ['tinymce'],
            },
            disableFields: ['autocomplete', 'button', 'file', 'header', 'paragraph', 'starRating', ],
            editOnAdd: true,
            fields: [{
                label: "Email",
                type: "text",
                subtype: "email",
                icon: "✉"
            }],
            formData: textArea.val().trim(),
            scrollToFieldOnAdd: true,
            stickyControls: {
                enable: true,
                offset: {
                    top: 20,
                    right: 20,
                    left: 'auto'
                }
            }
        };
        var formBuilder = $('#fb-editor').formBuilder(options);
        $("form").submit(function (e) {
            textArea.val(formBuilder.actions.getData('json'))
            $('#fb-editor :input').attr('disabled', true);
        });
    });
</script>
<style>
    .aligned label {
        float: none !important
    }
</style>
<textarea name="{{ widget.name }}" style="display:none" {% include "django/forms/widgets/attrs.html" %}>
    {% if widget.value %}{{ widget.value }}{% else %}[]{% endif %}
</textarea>

dynamic_forms/templates/dynamic_forms/widgets/formrender.html
<fieldset>
    {% for subfield in subfields %}
    {{subfield}}
    {% endfor %}
</fieldset>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

dynamic_forms/templates/dynamic_forms/widgets/subfield.html
{{label}}
{{field}}
<p>{{help_text}}</p>

dynamic_forms/templates/dynamic_forms/widgets/subfield_crispy.html
{% load crispy_forms_filters %}

{{field|as_crispy_field}}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}DyForms{% endblock %}</title>
</head>

<body>
{% block content %}
{% endblock %}
</body>

</html>

templates/build.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
    <a href="/">Back</a>
</form>
{% endblock %}

templates/form_detail.html
{% extends 'base.html' %}

{% block content %}
    <style>
        table, th, td {
            border: 1px solid black;
        }
        table, tr, td {
            text-align: center;
        }
    </style>
    <a href="{% url 'home' %}">Back to All Form</a>
    <br>
    <a href="edit/">Edit form</a>
    <br>
    <a href="{% url 'form_respond' object.pk %}">Respond To Form</a>

    <p>Responses</p>
    <hr>
    {% for formresponse in object.formresponse_set.all %}
        <ul>
            <table style="width:100%">
                <tr>
                    {% for k, v in formresponse.response.items %}
                        <th>{{ k }}</th>
                    {% endfor %}
                </tr>
                <tr>
                    {% for k, v in formresponse.response.items %}
                        <td>{{ v }}</td>
                    {% endfor %}
                </tr>
            </table>
        </ul>
        <hr>
    {% endfor %}
{% endblock %}

templates/form_edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
    <a href="#">Back</a>
</form>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'form_create' %}">Create New Form</a>

{% for i in form %}
<ul>
    <li><a href="{% url 'form_detail' i.pk %}">{{ i }}</a></li>
</ul>
{% endfor %}
</body>
</html>

templates/respond.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}